name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install deps
      run: sudo apt-get update && sudo apt install -y g++
    - name: Build Binary
      run: g++ -std=c++17 -O2 -o wg src/wg.cpp src/cli_handler.cpp src/gpu_utils.cpp -lyaml-cpp
    - name: Upload Binary
      uses: softprops/action-gh-release@v1
      with:
        files: wg
